source 'https://rubygems.org'

gem 'rails', '~> 6.0.0'
gem 'mongoid', '~> 7.3.0'
gem 'mongoid-paperclip'
gem 'mongoid_paranoia'
gem 'cancancan'
gem 'kaminari'
gem 'kaminari-mongoid'
gem 'kaminari-actionview'
gem 'devise'
gem 'aws-sdk'
gem 'aws-sdk-s3'
gem 'rack-throttle'
gem 'jbuilder'
gem 'httparty'
gem 'koala'
gem 'jwt'


gem 'ish_models', github: 'wasyaco/ish_models', branch: 'master'
gem 'ishapi'


group :development, :test do
  gem 'rspec-rails', '~> 5.1.0'
  gem 'simplecov'
  gem 'byebug'
  gem 'factory_bot_rails'
  gem 'database_cleaner-mongoid'
  gem 'rails-controller-testing'
end
