source 'https://rubygems.org'

gem 'rails', '5.1.4'
gem 'mongoid'
gem 'mongoid-paperclip'

gem 'ish_models', github: 'wasyaco/ish_models', branch: '1.5.0'
gem 'ishapi', github: 'wasyaco/ishapi', branch: '0.2.1'

gem 'cancancan'
gem 'kaminari'
gem 'kaminari-mongoid'
gem 'kaminari-actionview'
gem 'devise'
gem 'aws-sdk'
gem 'aws-sdk-s3'
gem 'rack-throttle'
gem 'jbuilder'
gem 'rails-controller-testing'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'simplecov'
  gem 'byebug'
  gem 'factory_bot_rails', require: false

  gem 'httparty'
  gem 'koala'
  gem 'jwt'
end
